### ISSUE TITLE
Please add "integer" in the expected class types for binarize()

### ISSUE THREAD

**Issue by AnikMallick** [business-science/correlationfunnel#3]
For columns that are read as an integer, binarize() is throwing an error. 

"Error: binarize(): [Unnacceptable Columns Detected] The following columns contain non-numeric or non-categorical data types"

**Comment by mdancho84** [comment]
Thanks for this. I will update to add integer.

**Comment by mdancho84** [comment]
Done - You can now use the developmental version. I will add to CRAN soon.
